# Generated by Django 5.0 on 2025-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_actives',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
