# Generated by Django 5.0 on 2025-01-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_is_actives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
    ]
