# Generated by Django 5.0 on 2025-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
